In [1]:
import numpy as np

In [2]:
my_array=np.array([[1,2,3],[4,5,6]])

In [3]:
my_array.ndim

2

In [4]:
my_array.size


6

In [12]:
array1=np.arange(1,10,2)
print(array1)

[1 3 5 7 9]


In [13]:
np.concatenate([array1,array1])

array([1, 3, 5, 7, 9, 1, 3, 5, 7, 9])

In [14]:
array1.mean()
array1.sum()

5.0

In [16]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [21]:
#100 e kadar 3,3 matris,30 büyükler boolean 
rand_array=np.random.randint(100,size=(3,3))
rand_array

array([[22, 71, 19],
       [56, 84, 47],
       [ 6, 10, 97]])

In [22]:
boolean_array=rand_array>30
boolean_array

array([[False,  True, False],
       [ True,  True,  True],
       [False, False,  True]])

In [23]:
rand_array[boolean_array]

array([71, 56, 84, 47, 97])

In [24]:
import pandas as pd

In [25]:
# pip-3 install pandas


In [30]:
g7_pop=pd.Series([35.467, 63.951, 80.940, 60.665])
g7_pop

0    35.467
1    63.951
2    80.940
3    60.665
dtype: float64

In [35]:
g7_pop.name="AA" 
g7_pop.values

array([35.467, 63.951, 80.94 , 60.665])

In [37]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

In [38]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64  
 2   Surface Area  7 non-null      int64  
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object 
dtypes: float64(2), int64(2), object(1)
memory usage: 412.0+ bytes


In [40]:
df.describe()

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [41]:
df.loc["Canada"]

KeyError: 'Canada'